package Intimate_matrimony_web;

import org.openqa.selenium.By;

import org.openqa.selenium.WebDriver;

public class base_testclass {
	public WebDriver driver;				
	public By username = By.xpath("//*[@id='loginModel_username']");
	public By loginpasswordfield = By.xpath("//*[@id='loginModel_password']");
	public By Year = By.xpath("//*[@id=\"eiYear\"]");
	public By loginbutton = By.xpath("//*[@id='formLogin']/div[4]/button");
	public By closepopupfield = By.xpath("//div[@class='closeBtn closeModalBtn' and @data-type='edu']");
	public By editbutton = By.xpath("/html/body/div[2]/div/div/div[1]/div[1]/div[3]/div[1]/div[2]");	
	public By aboutmyself = By.xpath("/html/body/div[2]/div/div/div[1]/div[3]/div/div[2]/div");
	public By descriptionfield = By.xpath("//*[@id=\"personal-info\"]");
	public By savebutton = By.xpath("//*[@id=\"form-About\"]/div[2]/button[1]");
	public By closepopup = By.xpath("/html/body/div[9]/div[1]/span");
	public By presentaddressfield = By.id("ta-presentaddress");
	public By permenantcheckbox = By.id("permanent");
	public By communicationaddress = By.id("permanent-communication");
	public By basicdetails = By.xpath("/html/body/div[2]/div/div/div[1]/div[4]/div/div/div[1]/div[2]/div");
	public By countrycode = By.xpath("//span[@class='select2-selection select2-selection--single' and @role='combobox']");
	public By countrycodesearchfield = By.xpath("/html/body/span/span/span[1]/input");
	public By maritalstatus = By.xpath("//span[@id='select2-select-marital-container']/ancestor::span[@class='select2-selection select2-selection--single']");
	public By maritalstatussearchfield = By.xpath("/html/body/span/span/span[1]/input");
	public By bodytype = By.xpath("//span[@aria-labelledby='select2-select-body-container']");
	public By bodytypesearchfield = By.xpath("/html/body/span/span/span[1]/input");
	public By physicalstatusdropdownfield = By.xpath("//span[@aria-labelledby='select2-select-physique-container']");
	public By Physical_status = By.xpath("//span[@aria-labelledby='select2-select-physique-container']");
	public By physicalstatussearchfield = By.xpath("/html/body/span/span/span[1]/input");
	public By complextion = By.xpath("//span[@aria-labelledby='select2-select-complexion-container']");
	public By complextionsearchfield = By.xpath("/html/body/span/span/span[1]/input");
	public By heightdropdownfield = By.xpath("//span[@aria-labelledby='select2-select-height-container']");
	public By heightsearchfield = By.xpath("/html/body/span/span/span[1]/input");
	public By weightfield = By.xpath("//span[@aria-labelledby='select2-select-weight-container']");
	public By Weightsearchfield = By.xpath("/html/body/span/span/span[1]/input");
	public By basicdetailssave = By.xpath("//button[@class='save save-data' and @data-type='BasicInfo']");
	public By editaddressbuttonfield = By.xpath("//div[@class='edit editItem' and @data-type='AddressInfo']");
	public By addresssavebuttonfield = By.xpath("//button[@class='save save-data' and @data-type='AddressInfo']");
	public By Religionedit = By.xpath("//div[@class='edit editItem' and @data-type='ReligionInfo']");
	public By castdropdownfield = By.xpath("//span[@aria-labelledby='select2-select-caste-container']");
	public By castsearchfield = By.xpath("//input[@class='select2-search__field']");
	public By Jadhakamdropdown = By.xpath("//span[@aria-labelledby='select2-select-jathakam-container']");
	public By Jadhakamsearchfield = By.xpath("/html/body/span/span/span[1]/input");
	public By stardropdownfield = By.xpath("//span[@aria-labelledby='select2-select-star-container']");
	public By searchfield = By.xpath("/html/body/span/span/span[1]/input");
	public By rashidropdown = By.xpath("//span[@aria-labelledby='select2-select-rasi-container']");
	public By rashisearchfiled = By.xpath("/html/body/span/span/span[1]/input");
	public By religionsavebutton = By.xpath("//button[@class='save save-data' and @data-type='ReligionInfo']");
	public By locationinfofield = By.xpath("/html/body/div[2]/div/div/div[1]/div[7]/div/div[1]/div[2]/div");
    public By countrydropdown = By.xpath("//span[@aria-labelledby='select2-select-country-container']");
    public By districtdropdownfield = By.xpath("//span[@aria-labelledby='select2-select-district-container']");
    public By editcareer = By.xpath("/html/body/div[2]/div/div/div[1]/div[8]/div/div[1]/div[2]/div");
    public By coursename = By.xpath("//*[@id=\"eiCourseName\"]");
	public By university_name = By.xpath("//*[@id=\"eiInstitutionName\"]");
	public By placename = By.xpath("//*[@id=\"eiPlace\"]");
	public By yearfield = By.xpath("//*[@id=\"eiYear\"]");
	public By addbuttonfield = By.xpath("//button[contains(@class, 'btnSaveCourse')]//span[text()='Add']");
	public By Saveducation = By.xpath("//button[@class='save save-details' and @data-type='EduInfo']");
	public By popupOkbuttonfield = By.xpath("//button[@class='cmnBtn' and text()=' OK']");
	public By editfamilydetailsfield = By.xpath("//div[@class='edit editItem' and @data-type='FamilyInfo']");
	public By fathernameinputfield = By.xpath("//input[@id='tb-father']");
	public By mothernameinputfield = By.xpath("//*[@id='tb-mother']");
	public By fatherjobdropdownfield = By.xpath("//span[@aria-labelledby='select2-select-fatherjobcat-container']");
	public By motherjobdropdown = By.xpath("//span[@aria-labelledby='select2-select-motherjobcat-container']");
	public By Fatherjobcategory = By.xpath("//span[@aria-labelledby='select2-select-fatherjob-container']");
	public By motherjobcategoryfield = By.xpath("//span[@aria-labelledby='select2-select-motherjob-container']");
	public By fathereducationdropdownfield = By.xpath("//span[@aria-labelledby='select2-select-fathereducat-container']");
	public By mothereducationdropdownfield = By.xpath("//span[@aria-labelledby='select2-select-mothereducat-container']");
	public By fathereducationdetailsfield = By.xpath("//span[@aria-labelledby='select2-select-fatheredudet-container']");
	public By mothereducationdetailsfield = By.xpath("//span[@aria-labelledby='select2-select-motheredudet-container']");
	public By familyvaluedropdownfield  = By.xpath("//span[@aria-labelledby='select2-select-famvalue-container']");
	public By Familytypedropdownfield = By.xpath("//span[@aria-labelledby='select2-select-famtype-container']");
	public By simarriagedropdown = By.xpath("//span[@aria-labelledby='select2-select-sismarried-container']");
	public By financialdropdownfield = By.xpath("//span[@aria-labelledby='select2-select-financialstatus-container']");
	public By familyinfosavebuttonfield = By.xpath("//button[@class='save save-data' and @data-type='FamilyInfo']");
	public By partnerpreferencefield = By.xpath("//div[contains(@class, 'editPreferenceItem') and @data-type='BasicPref']");
	public By heightfeetdropdownfield = By.xpath("//span[@id='select2-select-groomfeet-container']");
	public By heighttodropdownfield = By.xpath("//span[@id='select2-select-groominch-container']/ancestor::span[contains(@class,'select2-selection')]");
	public By basicinfosavebuttonfield = By.xpath("//button[@type='button' and @class='save save-data' and @data-type='BasicPref']");
	public By locationpreferenceeditbuttonfield = By.xpath("//div[@class='edit editItem editLocPreferenceItem' and @data-type='LocationPref']");
	public By otherpreferencesfield = By.xpath("//div[contains(@class,'editItem') and @data-type='OtherPref']");
	public By addcomments = By.xpath("//*[@id='other-comments']");
	public By Otherpreferencesavebutton = By.xpath("//button[@class='save save-data' and @data-type='OtherPref']");
	public By Careerinfoeditbutton = By.xpath("/html/body/div[2]/div/div/div[1]/div[9]/div/div[1]/div[2]/div");
	public By Occupationdropdown = By.xpath("(//span[@class='select2-selection select2-selection--single'])[19]");
	public By Occupationsearchbox = By.xpath("//input[@class='select2-search__field']");
	public By employedropdownfield = By.xpath("(//span[@class='select2-selection select2-selection--single'])[20]");
	public By employeesearchbox = By.xpath("//input[@class='select2-search__field']");
	public By Companyname = By.xpath("//*[@id=\"ciCompanyName\"]");
	public By designationfield = By.xpath("//*[@id=\"ciDesigination\"]");
	public By Placename = By.xpath("//*[@id=\"ciPlace\"]");
	public By year = By.xpath("//*[@id=\"ciFromYear\"]");
	public By toyear = By.xpath("//*[@id=\"ciToYear\"]");
	public By Careerinfofield = By.xpath("/html/body/div[2]/div/div/div[1]/div[9]/div/div[3]/div[2]/div[3]/div[3]/button[2]");
	public By Careersavefield = By.xpath("//button[@data-type='CareerInfo']");
	public By locationsavebuttonfield = By.xpath("//button[@data-type='LocationInfo']");
	//ffff
	//ddddd
}
